---
name: CI

on:
  - workflow_dispatch
  - push

jobs:

  check:
    runs-on: ubuntu-latest

    steps:
      - name: Set up build environment
        run: |
          sudo apt-get update && sudo apt-get install -y curl unzip gcc pkg-config gcc-multilib xvfb xdotool grim sway scrot libwayland-dev libx11-dev mesa-vulkan-drivers libxrandr-dev libxinerama-dev libxi-dev libxxf86vm-dev libx11-xcb-dev libxkbcommon-dev libxkbcommon-x11-dev libgles2-mesa-dev libegl1-mesa-dev libffi-dev libxcursor-dev libvulkan-dev

      - name: Checkout
        uses: actions/checkout@v5

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version-file: 'go.mod'

      # relevant docs:
      # - https://docs.github.com/en/actions/learn-github-actions/contexts#runner-context
      # - https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#setting-an-environment-variable
#      - name: Set env
#        run: |
#          echo "CGO_ENABLED=0" >> $GITHUB_ENV

      - name: Check
        run: go test -v ./...
...
